- name: Gets megaraid.py
  get_url:
    url: "{{ megaraid_datadog_check_script }}"
    dest: "{{ datadog_base_path }}/checks.d/"
    mode: 0755
  notify: Restart datadog-agent

- name: Deploys configuration
  template:
    src: megaraid.yaml.j2
    dest: "{{ datadog_base_path }}/conf.d/"
  notify: Restart datadog-agent
